name: re use
on: workflow_call
jobs:
  echo:
    strategy:
      matrix:
        node-version: [14, 18]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - node-version: 15
            os: ubuntu-latest
          - node-version: 16
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Echo Node version
        run: echo "Node version is ${{ matrix.node-version }} on ${{ matrix.os }}"
      - name: echos
        run: echo "Hello, World!"
